

GENERAL:
    #GPU_ID: "-1"
    GPU_ID: "0"
    MODE: "regular"


DATA:
    TRAIN_DATA_PATH: "/home/gbmc/recolour/data/tiny-imagenet-200/val/images"
    VAL_DATA_PATH: "/home/gbmc/recolour/data/tiny-imagenet-200/val/images/"
    TEST_DATA_PATH: "/home/gbmc/recolour/data/tiny-imagenet-200/test/images/"


MODEL:
    ARCHITECTURE: "UNetFCNN"
    #ARCHITECTURE: "SmallUNetFCNN"
    
    #IMG_DIM: [256, 256]
    IMG_DIM: &IMG_DIM [64, 64]


PARAMS:
    img_dim: *IMG_DIM


TRAIN:
    EPOCHS: 10000
    STEPS_PER_EPOCH: 50
    BATCH_SIZE: 32
    #BATCH_SIZE: 2
    LEARNING_RATE: 0.001
    PREDICTION_PERIOD: 5
    MODEL_SAVE_PERIOD: 50
    SHUFFLE: True
    #TRAIN_SAMPLES: 2
    TRAIN_SAMPLES: 0


VAL:
    VALIDATION_SAMPLES: 16


TEST:



VIS:
    VIS_SAMPLES: 3 

