

GENERAL:
    #GPU_ID: "-1"
    GPU_ID: "0"
    MODE: "GAN"


DATA:
    TRAIN_DATA_PATH: "/home/hboekema/Projects/recolour/data/tiny-imagenet-200/train/"
    VAL_DATA_PATH: "/home/hboekema/Projects/recolour/data/tiny-imagenet-200/val/images/"
    TEST_DATA_PATH: "/home/hboekema/Projects/recolour/data/tiny-imagenet-200/test/images/"


MODEL:
    #IMG_DIM: &IMG_DIM [256, 256]
    #IMG_DIM: &IMG_DIM [128, 128]
    IMG_DIM: &IMG_DIM [64, 64]


GENERATOR:
  #ARCHITECTURE: "FCNN"
    ARCHITECTURE: "WGAN_FCNN"
    GEN_LEARNING_RATE: 0.0005
    RUNS_PER_EPOCH: 2


GEN_PARAMS:
    img_dim: *IMG_DIM


DISCRIMINATOR:
    ARCHITECTURE: "SimpleDCNN"
    DISC_LEARNING_RATE: 0.0005
    RUNS_PER_EPOCH: 3


DISC_PARAMS:
    img_dim: *IMG_DIM


TRAIN:
    EPOCHS: 10000
    STEPS_PER_EPOCH: 50
    BATCH_SIZE: 32
    #BATCH_SIZE: 2
    PREDICTION_PERIOD: 5
    MODEL_SAVE_PERIOD: 50
    SHUFFLE: True
    #TRAIN_SAMPLES: 2
    TRAIN_SAMPLES: 0


VAL:
    VALIDATION_SAMPLES: 16


TEST:



VIS:
    VIS_SAMPLES: 5

